### ISSUE TITLE
cannot load plugin in QGIS 3.16 for macOS

### ISSUE THREAD

**Issue by EJFuchs** [alexbruy/processing-circuitscape#10]
I've installed the plugin via zip file. the plugin installed, however it did not load do to the following error:

> Couldn't load plugin 'processing-circuitscape-master' 
> 
> ModuleNotFoundError: No module named 'processing_circuitscape' 
> Traceback (most recent call last):
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
>     __import__(packageName)
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/Eric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing-circuitscape-master/__init__.py", line 28, in 
>     from processing_circuitscape.circuitscapeProviderPlugin import CircuitscapeProviderPlugin
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'processing_circuitscape'
> 

I'm running macOS high Sierra and QGIS 3.16.

**Comment by alexbruy** [comment]
Install plugin from repository.
