### ISSUE TITLE
problem with plugin

### ISSUE THREAD

**Issue by BenGuinaudeau** [alexbruy/processing-circuitscape#8]
Hello there,

I have installed the pluggin (QGIS 3.8) here :
C:\Program Files\QGIS 3.8\apps\qgis\python\plugins\processing-circuitscape
I can see it on QGIS : 
![image](https://user-images.githubusercontent.com/52285803/60269202-493ec680-98ee-11e9-883c-02d9e0931eef.png)
I also have installed circuitscape on my computer

but I can't see in providers : 
![image](https://user-images.githubusercontent.com/52285803/60269338-90c55280-98ee-11e9-8d6a-a765952b2643.png)

do you know what to do to configure new provider ?

kind regards

Ben

**Comment by alexbruy** [comment]
@BenGuinaudeau looks like you are doing something wrong when installing plugin. I suspect you have installed it manually instead of installing from the repository using Plugin Manager.

**Comment by BenGuinaudeau** [comment]
Yes that's true ! when I use this way : 
![image](https://user-images.githubusercontent.com/52285803/60270399-a0de3180-98f0-11e9-989b-c62d3cd7db98.png)

I get a message error : 
ll last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Circuitscape'


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.8.0-Zanzibar Zanzibar, 11aff65f10 

Chemin Python :
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/Benjamin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Benjamin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Benjamin/AppData/Roaming/QGIS/QGIS3\profiles\default/python

what's wrong ?

**Comment by alexbruy** [comment]
You downloaded **source** archive from GitHub.

Please, never use files from GitHub unless you perfectly undestand why you need them and how to use them. There is a **repository** with all my plugins, use it to install plugins, not GitHub. If you don't know how to use QGIS Plugin manager there is a chapter about it in the QGIS documentation.
