### ISSUE TITLE
Couldn't load plugin 'processing-circuitscape-master' 

### ISSUE THREAD

**Issue by neigun** [alexbruy/processing-circuitscape#9]
OS Ubuntu 19.10
QGIS 3.10

I may be missing the obvious, but I get the following error when I try and install the Circuitscape plugin:

Couldn't load plugin 'processing-circuitscape-master' 

ModuleNotFoundError: No module named 'processing_circuitscape' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing-circuitscape-master/__init__.py", line 28, in 
    from processing_circuitscape.circuitscapeProviderPlugin import CircuitscapeProviderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_circuitscape'

Python version: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008] 
QGIS version: 3.10.0-A Coruña A Coruña, 413de47e3b 

To try and install the plugin I have downloaded the zip and use Plugins Install from ZIP

**Comment by alexbruy** [comment]
Indeed you are missing obvious. Never use files from GitHub unless you are know why you need then and how to use them. GitHub is for developers. Users should use plugin repository.

**Comment by neigun** [comment]
Hi Alex,

Whilst it may appear obvious not to use Github, other developers direct people to their page to download the code.  Having read some other posts, it is now obvious what I need to do, but I might suggest it would be helpful to include a short paragraph in your repository about how to add it to QGIS.  At the very least, it would stop posts like mine ;-) Keep up the good work it's much appreciated.

Neil
